[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.0.1"

[[constraint]]
  name = "github.com/uudashr/iso8601"
  branch = "master"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "v1.2.0"
